name: Dependabot auto-merge
on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: ["20"]
        java: ["17"]
    runs-on: ${{ matrix.os }}
    if: ${{ github.actor == 'dependabot[bot]' || (github.event.pull_request.user.login == 'dependabot[bot]' && github.actor == '@khalilou88') }}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          cache: "npm"

      - name: Install dependencies
        run: npm i

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: ${{ matrix.java }}

      - name: Tests
        id: tests
        run: npm run nx run-many -- --target=test --parallel=1
        env:
          NX_VERBOSE_LOGGING: "true"
          GITHUB_ACTIONS: "true"

      - name: Enable auto-merge for Dependabot PRs
        if: steps.tests.outcome == 'success'
        run: gh pr merge --auto --rebase "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
