name: Libs
on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"

jobs:
  Run_checks:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        node_version: ["20"]
        java: ["17"]
      fail-fast: false
    env:
      NX_VERBOSE_LOGGING: "true"
      NX_MAVEN_CLI_OPTS: "--no-transfer-progress -Dmaven.plugin.validation=VERBOSE"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: nrwl/nx-set-shas@v3

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
          cache: "npm"

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: ${{ matrix.java }}

      - name: Install dependencies
        run: npm i

      - name: Maven-checkstyle-lint
        run: npm run nx maven-checkstyle-lint m-m-lib

      - name: Ktlint
        run: npm run nx ktlint m-sb-kt-lib

      - name: Ktlint-format
        run: npm run nx ktlint-format m-q-kt-lib

      - name: Unit tests
        run: npm run nx test m-q-lib

      - name: Build
        run: npm run nx build m-sb-lib
